name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set a timeout for the entire build and deploy job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set file permissions
      run: chmod 644 .git/config

    - name: Configure git
      run: |
        git config --local --name-only --get-regexp http.https://github.com/.extraheader
        git config --local --unset-all http.https://github.com/.extraheader

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
        echo "Dependencies installed."

    - name: Install Vite
      run: |
        echo "Installing Vite..."
        npm install vite
        echo "Vite installed."

    - name: Build the project
      run: |
        echo "Building the project..."
        npm run build
        echo "Build completed."

    - name: Deploy the project
      run: |
        echo "Deploying the project..."
        npm run deploy
        echo "Deploy completed."

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_HILL_0A4A95003 }}
          action: "close"
